---
title: "Using Pipe Operators"
author: "Ibrahim Radwan"
date: "2023-09-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required Libraries
Here we import the required libraries
```{r}
library(tidyverse)
library(nycflights13)
```

## Problem
Imagine that we want to explore the relationship between the distance and 
average delay for each location. 

### scenario 1, using multiple subsequent operations/function
```{r}

by_dest <- group_by(flights, dest) 
# extract the number of flights, average distance and average delay for each destination 
dest_delay_relation <- summarise(by_dest, count= n(), dist= mean(distance, na.rm = TRUE), delay= mean(arr_delay, na.rm = TRUE) ) 
# visualise to understand the relationship 
ggplot(data= dest_delay_relation, mapping=aes(x= dist, y= delay)) + 
  geom_point(aes(size= count), alpha= 1/ 3) + 
  geom_smooth()

# you may filter out the destinations with minimal number of flights 
dest_delay_relation2 <- filter(dest_delay_relation, count > 20, dest != 'HNL')
#, and visualise again
ggplot(data= dest_delay_relation2, mapping=aes(x= dist, y= delay)) + 
  geom_point(aes(size= count), alpha= 1/ 3) + 
  geom_smooth()

```

### scenario 2, using pipe operators
```{r}

dest_delay_relation3 <- flights %>%  
  group_by(dest) %>% 
  summarise(count= n(), dist= mean(distance, na.rm = TRUE), delay= mean(arr_delay, na.rm = TRUE)) %>% 
  filter(count > 20, dest != 'HNL') # the filter step is to remove the outlier

# and visualise --> visualisation can be also done in the previous step
ggplot(data= dest_delay_relation3, mapping=aes(x= dist, y= delay)) + 
  geom_point(aes(size= count), alpha= 1/ 3) + 
  geom_smooth()

```
