---
title: "Lab 5 - Matrices, Arrays and Data Frames"
author: "Ajul Thomas"
date: "2023-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matrices and Arrays
---

```{r}

mat <- matrix(11:80, 7, 10)
print(mat)
str(mat)

arr <- array(1:60, dim= c(3,4,5))
print(arr)
str(arr)


```

### Excercise 1

```{r}

vecX <- c(3, 9, -1, 4, 2, 6)
vecY <- c(5, 2, 0, 9, 3, 4)

# Create a matrix matX, from the vector (vecX), where number of rows are 2,

matX <- matrix(vecX, 2)
print(matX)

# Create a matrix matY, from the vector (vecY), where number of rows are 2,
matY <- matrix(vecY, 2)
print(matY)

# Display the values of elements of the first row from matrix matX.
print(matX[1,])

# Display the value of the element in the second row and third column of matY,
print(matY[2,3])

# Sum up the two matrices and display the output,
matSum = matX + matY
print(matSum)

# Subtract the matY from matX and display the output,
matDifference = matX - matY
print(matDifference)

# Multiply the two matrices (element-wise) and print the output,
matProductE = matX * matY
print(matProductE)

# Transpose the matY and assign the output to a third matrix called matZ,
matZ = t(matY)
print(matZ)

# Perform matrix multiplication between matX and matZ and assign the output to matW,
matW = matX %*% matZ
paste(matW)

# Display the dimension of the matW matrix,
paste("Dimension of the matW, which stores the output of matrix multiplication between matX and matZ is ", )
print(dim(matW))

# Display the maximum, minimum and average value of matrix, matW
maximum = max(matW)
paste("maximum value in matW is", maximum)

minimum = min(matW)
paste("minimum value in matW is", minimum)

average = mean(matW)
paste("average of values in matW is", minimum)

# Reflect and discuss with your colleagues what matrices are and when we should use them.

```

### Excercise 3

```{r}


vecZ <- c(8, -3, 1, 7, 0, 4)
# print the three vectors, vecX, vecY, vecZ

print(vecX)
print(vecY)
print(vecZ)

# Create an array from the three vector and give it a name (e.g., arrNums). The dimension of this array is (3,2,3)
arrNums <- array(c(vecX,vecY,vecZ), dim = c(3,2,3))

# what is the element of the second row and first column of the third slice of the array
element <- arrNums[2,1,3]
  
# print this element
print(element)

# extract the minimum, maximum, median, and mean of the values in the array.

cat(max(arrNums))
min(arrNums)
median(arrNums)
mean(arrNums)

```

### Excercise 3

```{r}

authors=c("Reda", "John", "Edward", "Ben")
year=c(2104, 2016, 2005, 2019)
publishers=c("Wiley", "Springer", "Sage", "International Books")

books <- data.frame(authors=authors, year= year, publishers= publishers)

# print the data frame entries
print(books)

# print the values of the authors entry
books$authors
# or ...
books["authors"] 

# what will happen if you use double square brackets? books[["authors"]] 
# the df will be displayed as a subset of dataframe

books[1,2]

```

### Excercise 3
---

```{r}



```

