---
title: "Lab 4 - Vectors"
author: "Ajul Thomas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Exercise 1

```{r}

vecX <- c(9, -1, 4, 2)           
cat("Original Vector: ")   
print(vecX)

# Append 3 at the start of the vector
vecX <- c(3, vecX)
cat("Appending 3 at the start of the vector: ")
print(vecX)

# Append 6 at the end of the vector
vecX <- c(vecX, 6)
cat("Appending 6 at the end of the vector: ")
print(vecX)

# Append another vector at the end of the vector
tempVector <- c(-7, 12)
vecOut <- c(vecX, tempVector)
cat("Appending another vector at the end of the vector: ")
print(vecOut)

```

## Exercise 2

```{r}

ids <- c(1001, 1002, 1003, 1004, 1005)
names <- c("Alice", "Bob", "Charlie", "David", "Eve")

class(ids)
class(names)

```
```{r}

# search_ids = c(1003, 1005, 1007)

new_search_id = sample(x=1000:1020,size = 1)

for (id in new_search_id) {
  if (id %in% ids){
    
    #print(ids==id)
    
    name <- names[ids==id]
    
    cat("The student with ID ", id, " is ", name, "\n")
  }
  else {
    cat("The student with ID ", id, " is not in the database.", "\n")
  }
}

```
```{r}

ids <- c(1001, 1002, 1003, 1004, 1005)
names <- c("Alice", "Bob", "Charlie", "David", "Eve")

id = 1001

bool_vector <- ids==id

names[bool_vector]

```

```{r}

new_search_id = sample(x=1000:1020,size = 1)


```


## Exercise 3

```{r}

numbers <- c(1, 3, 5, 7, 9)
sum <- 0
for (n in numbers){
  if(n %% 2 != 0) {
    sum = sum + n
  }
}
print(sum)
```

## Excercise 4

```{r}

firstnames <- c("John", "Jane", "David")
lastnames <- c("Doe", "Smith", "Jones")

fullnames <- c()

for (index in 1:length(firstnames)) {
  fullnames <- c(fullnames, paste(firstnames[index], lastnames[index]) )
}

cat(fullnames, sep = "\n")

```

## Excercise 5

```{r}
n=15
for(i in 1:n){
  no_of_stars <- 2*i- 1
  no_of_spaces <- n-i
  if(no_of_spaces > 0) {
    for(j in 1:no_of_spaces){
      cat(" ")
    }
  }
  if(no_of_stars > 0) {
    for(k in 1:no_of_stars) {
      cat("*")
    }
  }
  cat("\n")
}

```

